spring:
  application:
    name: live-coding-cfao-backend

  # database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/live_db
    username: diallodev
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

# server
server:
  port: 8081

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

